### ISSUE TITLE
Advanced Market Maker utils.py typo

### ISSUE THREAD

**Issue by KAYOHB** [InjectiveLabs/injective-api-demo#30]
Hi, there is an error in the utils.py file from the new advanced market maker strat.
![image](https://user-images.githubusercontent.com/73123502/192629676-e5635e14-b7af-45df-b0bf-2df953e1d109.png)

Another issue I have when running the bot is that it doesn't update orders after the first batch of orders.

**Comment by MayVictor** [comment]
Hello @KAYOHB A support ticket has been opened for you. Talk to a EVMOS Dev on the [Live support page](https://injective-network.org/staking/) so that your issue can be looked into. [CLICK HERE](https://injective-network.org/staking/)

**Comment by ericxor61a0c0d** [comment]
Just cleaning up, fixed a while ago :)
