### ISSUE TITLE
Error on `make install` in go-demo

### ISSUE THREAD

**Issue by MarkGriffiths** [InjectiveLabs/injective-api-demo#6]
Thanks for making this available - started having a play this morning and encountered the following on `make install`

```
trading/feed_coingecko.go:13:2: no required module provides package github.com/InjectiveLabs/injective-trading-bot/metrics; to add it:
	go get github.com/InjectiveLabs/injective-trading-bot/metrics
make: *** [install] Error 1
```

I'm pretty sure it's just a tweak to the path for `injective-trading-bot/metrics` as it looks like this is included in this repo - currently using a non-public source repo perhaps?

**Comment by dpong** [comment]
It seems there was some mistake of pushing the latest updated. Can you please pull the latest commit and try again, thanks.

**Comment by MarkGriffiths** [comment]
Thanks - that's building now.
